# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Signature Podcast
email: bill@digitalsignature.fm
description: "Join us for meaningful conversations with higher education faculty, administrators, students, and alumni, as well as industry leaders (both in the technology sector and in diverse domain areas with technical demand) to discuss these different pathways, the kinds of skills they utilize that one might encounter in primary and secondary school, and the kinds of careers they can lead to.  These interviews will be of interest to a broad audience, including parents, K-12 teachers and counselors, and students, and will showcase technical demos and examples that highlight the potential to apply computing in various ways that you can try at home."
subtitle: "Conversations and Activities about Career Pathways in Computing."
lang: en-us
author: William M. Mongan
copyright: "&#xA9; 2022"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.digitalsignature.fm" # the base hostname & protocol for your site
twitter_username: BillJr99
github_username:  BillJr99

permalink: /:year/:title.html

#Timezone
timezone: America/New_York

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

# Additional collections beyond _pages and _posts
collections:
  activities:
    output: true